name: Validate gentx PR

on:
  pull_request:
    paths:
      - "mainnet/gentx/**.json"   # run only when gentx files change
      - ".github/workflows/**"    # …or the workflow itself

jobs:
  validate-gentx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0        # we need full history for diffs

      - name: Install tooling (jq + lumerad)
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y jq curl
          curl -L \
            https://github.com/LumeraProtocol/lumera/releases/download/v1.1.0/lumera_v1.1.0_linux_amd64.tar.gz \
            -o lumera_v1.1.0_linux_amd64.tar.gz
          tar -xzf lumera_v1.1.0_linux_amd64.tar.gz
          chmod +x lumerad
          sudo mv lumerad /usr/local/bin/
          sudo mv libwasmvm.x86_64.so /usr/liblum/

      - name: Run CI validation script
        run: |
          bash scripts/ci/validate_gentx.sh
