name: Validate gentx PR
# Updated to trigger validation for existing PRs

on:
  pull_request:
    paths:
      - "mainnet/gentx/**.json"   # run only when gentx files change
      - ".github/workflows/**"    # …or the workflow itself
  workflow_dispatch:              # allow manual triggering
    inputs:
      pr_number:
        description: 'PR number to validate (optional)'
        required: false
        type: string

jobs:
  validate-gentx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0        # we need full history for diffs

      - name: Checkout PR if specified
        if: github.event.inputs.pr_number
        run: |
          gh pr checkout ${{ github.event.inputs.pr_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for gentx files
        run: |
          if [ ! -d "mainnet/gentx" ] || [ -z "$(ls -A mainnet/gentx/*.json 2>/dev/null)" ]; then
            echo "No gentx files found in mainnet/gentx/ directory"
            echo "This workflow validates gentx files in PRs that add files to mainnet/gentx/"
            exit 0
          fi
          echo "Found gentx files to validate:"
          ls -la mainnet/gentx/*.json

      - name: Install tooling (jq + lumerad)
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y jq curl
          curl -L \
            https://github.com/LumeraProtocol/lumera/releases/download/v1.1.0/lumera_v1.1.0_linux_amd64.tar.gz \
            -o lumera_v1.1.0_linux_amd64.tar.gz
          tar -xzf lumera_v1.1.0_linux_amd64.tar.gz
          chmod +x lumerad
          sudo mv lumerad /usr/local/bin/
          sudo mv libwasmvm.x86_64.so /usr/local/lib/
          sudo ldconfig

      - name: Run CI validation script
        run: |
          bash scripts/ci/validate_gentx.sh
